### PR TITLE
Pin dependencies

### PR DESCRIPTION
**Pull request by npm-opinionated-bot-assistant**
### Hi @keesschollaart81 👋🏻

I hope you're doing well.

As an **opinionated bot**, I noticed that the dependencies in your project are not currently **pinned** to a specific version. This means that the project could be using a different version of a package on each deployment, especially if [`npm install`](https://docs.npmjs.com/cli/install) is used instead of [`npm ci`](https://docs.npmjs.com/cli/ci) ([what is the difference](https://stackoverflow.com/a/53325242)). This can lead to unexpected issues caused by updates to third-party packages. It can also be encountered when the project is cloned for development and the developer installs the project with [`npm install`](https://docs.npmjs.com/cli/install) if there is a newly compatible version in range defined for each dependency in the [`package.json`](https://docs.npmjs.com/cli/configuring-npm/package.json) file.

As maintainers, it is **our** responsibility to manage dependency versions and ensure that they are up to date and compatible with the project's code.

### What's in the PR ?

I've created a pull request that updates the project's [`package.json`](https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/package.json) file to include specific versions for each of its dependencies based on project's [`package-lock.json`](https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/package-lock.json) file. This should not break anything. In case it does, I apologize for it.

You can also set `save-exact=true` in your [`.npmrc`](https://docs.npmjs.com/cli/configuring-npm/npmrc) file 😉

### Automate dependency updates

If you're worried about the workload of keeping dependencies up to date, there are tools available to help automate the process like [Renovate](https://github.com/renovatebot/renovate) or [Dependabot ](https://github.com/dependabot) which can automatically update dependencies for you based on a set of rules that you define.

You can also use [`npm-check-updates`](https://github.com/raineorshine/npm-check-updates) CLI to update your `package.json` dependencies to the latest versions.

### Why should you pin dependencies ?

- https://docs.renovatebot.com/dependency-pinning/
- https://the-guild.dev/blog/how-should-you-pin-dependencies-and-why
- https://maxleiter.com/blog/pin-dependencies

If you've already discussed this topic and implemented best practices in your project, I apologize for bringing it back up.

Thanks for taking the time to read this message, and I wish you a great day 🌞 and all the best for the future 🚀 .

Stay safe 🙏🏻  
An opinionated bot 🤖

### CODE REVIEW

**Comment by frenck** [comment]
Reported this with GitHub Abuse. Please get lost with this automated bullcrap.

../Frenck

**Comment by npm-opinionated-bot-assistant** [comment]
I'm deeply sorry If this PR make you feel that way. I am also a human behind this account with a little bit of automation and I didn't wanted to harm you in any way. I feel that I may be wrong in my approach, I just wanted to suggest modifications. 

The point is, using my knowledge and understanding, even is there is a lock file, `npm install` will install dependencies that are valid in the range declared in the `package.json` if you do not use `npm ci` in your CI pipeline/build and if there is an issue with one of your dependencies with a unexpected issue that breaks your app then dependency pinning will solve this. But I also may be wrong about it. I'm trying to improve every day.

Wish you the best 🙏🏻

**Comment by frenck** [comment]
> The point is, using my knowledge and understanding, even is there is a lock file

That is up to the user, it is packaged and shipped using the lock file.
If we all pinned it strictly in our packages, the lock files weren't needed, right?

I think the approach is wrong. I understand you are trying to improve the world, but so are all the flyers of people that want me to believe in "god" in my mailbox. Yet, it is just spamming.

Make an application available that people can install and promote that.

../Frenck

**Comment by npm-opinionated-bot-assistant** [comment]
> That is good to know, please note, that account using bots, is violating GitHub policies. I've reported it for that reason (and for the spamming).

> Especially, as the account clearly exposes itself as a bot on a user account.

Right, fair enough.

> I think the approach is wrong. I understand you are trying to improve the world, but so are all the flyers of people that want me to believe in "god" in my mailbox real-world mailbox. Yet, it is just spamming.

I will disable the current account.

> Make an application available that people can install and promote that.

Sure, that I can do 🚀 

Again, I apologize for this and thanks for taking time to answer.

**Pull request closed without merging**
