### PR TITLE
Add respond_to_read to KNX switch

### PR DESCRIPTION
**Pull request by farmio**
Add respond_to_read to KNX switch
https://github.com/home-assistant/core/pull/51790

### CODE REVIEW

**Review by frenck — APPROVED** [review]
✅ Approved. Can be merged as soon as the parent PR gets merged.

**Comment by farmio** [comment]
Tbh I don't know TypeScript at all and also have no test environment for this. 

The current lint error doesn't seem point out where the problem is. Can someone help me out here please?

**Comment by frenck** [comment]
It is prettier that is complaining about file formatting.

`npx prettier --write <file>`

If you don't have such an env, just leave it and I'll pick it up.

**Comment by farmio** [comment]
That would be great, thanks Frenck!

**Pull request merged**
