### PR TITLE
Update template.ts to include 2013.3 fan change

### PR DESCRIPTION
**Pull request by ryanjohnsontv**
Adds support for new fan template configuration variables updated in 2021.3

### CODE REVIEW

**Review by frenck — CHANGES_REQUESTED** [review]
Please run `prettier` to format the file you've changed so the build can pass.

Thanks! 👍

**Comment by ryanjohnsontv** [comment]
Apologies, running Prettier doesn't seem to have any changes on the code inside of VsCode. I'm not sure what's causing the compiling error.

**Comment by ryanjohnsontv** [comment]
Fixed! I love being wrong; permissions issue on my remote VsCode instance led to Prettier not running properly.

**Review by frenck — APPROVED** [review]
Awesome! Thanks! 👍

**Pull request merged**
