### PR TITLE
Eslint path fix for windows

### PR DESCRIPTION
**Pull request by bohmandan**
Tested on:
* Windows 10 (Git Bash)
* Windows 10 (Powershell)
* Ubuntu 20.04 (WSL2)

### CODE REVIEW

**Comment by bohmandan** [comment]
Oops, saw the failed test, weird.
Troubleshooting continues...

**Comment by frenck** [comment]
@bohmandan Could you make sure the build passes?

**Comment by bohmandan** [comment]
> @bohmandan Could you make sure the build passes?

Yes, work is ongoing...

**Comment by bohmandan** [comment]
Ok now it works, updated "test information" above too.

**Review by frenck — APPROVED** [review]
Awesome! Thanks, @bohmandan 👍 

Happy Hacktoberfest 🎉

**Pull request merged**
